/// Flutter icons MyFlutterAppSecond
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterAppSecond
///      fonts:
///       - asset: fonts/MyFlutterAppSecond.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterAppSecond {
  MyFlutterAppSecond._();

  static const _kFontFam = 'MyFlutterAppSecond';

  static const IconData money = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData newspaper = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData destination = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData calendar = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData shop = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData cancel = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData checked = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData driver = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData pin = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData music_player = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData conversation = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData no_smoking = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData attach = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData passenger = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData email = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData car_seat_with_seatbelt = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData pharmacy = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData medicine = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData zip = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData credit_card = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData multimedia = const IconData(0xe814, fontFamily: _kFontFam);
}
