name: shouz
description: Shouz, les actualités, les deals du moment, les évènements et vos voyages sont à portée de main.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+4

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  curved_navigation_bar: ^1.0.3
  simple_gradient_text: ^1.2.3
  flutter_staggered_grid_view: ^0.6.2
  url_launcher: ^6.1.5
  location: ^4.4.0
  huawei_location: ^6.0.0+303
  latlong2: ^0.8.1
  flutter_map: ^3.0.0
  loading_indicator: ^3.1.0
  geocoding: ^2.0.5
  fluttertoast: ^8.0.9
  share_plus: ^4.1.0
  uni_links: ^0.5.1
  path_provider: ^2.0.11
  flutter_svg: ^1.1.5
  dotted_border: ^2.0.0+2
  image_picker: ^0.8.5+3
  awesome_notifications: ^0.7.0-beta.6
  shared_preferences: ^2.0.15
  video_player: ^2.4.7
  http: ^0.13.5
  sqflite: ^2.0.3+1
  flutter_typeahead: ^4.1.0
  skeleton_text: ^3.0.0
  file_picker: ^5.0.1
  provider: ^6.0.3
  socket_io_client: ^2.0.0
  carousel_slider: ^4.1.1
  timeline_tile: ^2.0.0
  qr_code_scanner: ^1.0.1
  audioplayers: ^1.0.1
  permission_handler: ^10.0.0
  device_info_plus: ^4.1.2
  record: ^4.4.0
  firebase_messaging: ^13.0.1
  firebase_core: ^1.22.0
  onesignal_flutter: ^3.4.1
  huawei_push: ^6.5.0+300
  animated_text_kit: ^4.2.2
  video_compress: ^3.1.1
  intl: ^0.17.0
  syncfusion_flutter_charts: ^20.2.49
  cached_network_image: ^3.2.2
  flutter_native_splash: ^2.2.9
  badges: ^2.0.3
  flutter_hms_gms_availability: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.10.0

  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "images/icon/ic_launcher2.png"

flutter_native_splash:
  color: "#2d3447"
  image: images/icon/app_icon.png

  android_12:
    image: images/icon/app_icon.png
    icon_background_color: "#2d3447"

  web: false

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: LexendExa
      fonts:
        - asset: fonts/LexendExa-Regular.ttf
    - family: PTsans
      fonts:
        - asset: fonts/PTSans-RegularItalic.ttf
    - family: MyFlutterApp
      fonts:
        - asset: icons/MyFlutterApp.ttf
    - family: MyFlutterAppSecond
      fonts:
        - asset: icons/MyFlutterAppSecond.ttf
    - family: Montserrat-Black
      fonts:
        - asset: fonts/Montserrat-Black.ttf
    - family: Montserrat-Light
      fonts:
        - asset: fonts/Montserrat-Light.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
