name: shouz
description: Shouz, les actualités, les deals du moment, les évènements et vos voyages sont à portée de main.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  curved_navigation_bar: ^1.0.3
  simple_gradient_text: ^1.2.2
  flutter_staggered_grid_view: ^0.6.1
  url_launcher: ^6.0.9
  location: ^4.3.0
  huawei_location: ^6.0.0+302
  latlong2: ^0.8.1
  flutter_map: ^0.14.0
  loading_indicator: ^3.0.3
  geocoding: ^2.0.4
  fluttertoast: ^8.0.9
  share_plus: ^3.1.0
  uni_links: ^0.5.1
  path_provider: ^2.0.9
  flutter_svg: ^1.0.3
  dotted_border: ^2.0.0+2
  image_picker: ^0.8.5
  awesome_notifications: ^0.7.0-beta.2
  shared_preferences: ^2.0.13

  video_player: ^2.3.0
  http: ^0.13.4
  sqflite: ^2.0.2
  flutter_typeahead: ^3.2.4
  skeleton_text: ^3.0.0
  file_picker: ^4.5.1
  provider: ^6.0.2
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  carousel_slider: ^4.0.0
  timeline_tile: ^2.0.0
  qr_code_scanner: ^0.7.0
  audioplayers: ^0.20.1
  permission_handler: ^9.2.0
  device_info_plus: ^3.2.2
  record: ^3.0.4
  firebase_messaging: ^11.2.14
  firebase_core: ^1.15.0
  onesignal_flutter: ^3.3.0
  huawei_push: ^6.3.0+304

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^1.0.4

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "images/icon/ic_launcher2.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: LexendExa
      fonts:
        - asset: fonts/LexendExa-Regular.ttf
    - family: PTsans
      fonts:
        - asset: fonts/PTSans-RegularItalic.ttf
    - family: MyFlutterApp
      fonts:
        - asset: icons/MyFlutterApp.ttf
    - family: MyFlutterAppSecond
      fonts:
        - asset: icons/MyFlutterAppSecond.ttf
    - family: Montserrat-Black
      fonts:
        - asset: fonts/Montserrat-Black.ttf
    - family: Montserrat-Light
      fonts:
        - asset: fonts/Montserrat-Light.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
