name: shouz
description: Shouz, les actualités, les deals du moment, les évènements et vos voyages sont à portée de main.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.28+28

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.3
  simple_gradient_text: ^1.3.0
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.1.14
  location: ^5.0.3
  huawei_location: ^6.11.0+301
  latlong2: ^0.9.0
  loading_indicator: ^3.1.1
  geocoding: ^2.1.0
  fluttertoast: ^8.2.2
  share_plus: ^7.1.0
  uni_links: ^0.5.1
  path_provider: ^2.1.1
  flutter_svg: ^2.0.7
  dotted_border: ^2.1.0
  image_picker: ^1.0.4
  awesome_notifications: ^0.8.2
  shared_preferences: ^2.2.1
  video_player: ^2.7.2
  http: ^1.1.0
  sqflite: ^2.3.0
  flutter_typeahead: ^4.8.0
  skeleton_text: ^3.0.1
  file_picker: ^5.5.0
  provider: ^6.0.5
  socket_io_client: ^2.0.3+1
  carousel_slider: ^4.2.1
  timeline_tile: ^2.0.0
  qr_code_scanner: ^1.0.1
  permission_handler: ^11.0.1
  record: ^4.4.4
  firebase_messaging: ^14.6.9
  firebase_core: ^2.17.0
  huawei_push: ^6.10.0+300
  animated_text_kit: ^4.2.2
  video_compress: ^3.1.2
  intl: ^0.18.1
  syncfusion_flutter_charts: ^23.1.39
  syncfusion_flutter_gauges: ^23.1.39
  cached_network_image: ^3.3.0
  badges: ^3.1.2
  flutter_hms_gms_availability: ^3.7.0
  mapbox_gl: ^0.16.0
  flutter_slidable: ^3.0.0
  ticket_widget: ^0.0.1
  flutter_expandable_fab: ^2.0.0
  adaptive_action_sheet: ^2.0.2
  flutter_rating_bar: ^4.0.1
  photo_view: ^0.14.0
  in_app_review: ^2.0.6
  flutter_tts: ^3.8.3
  audioplayers: ^5.2.0
  font_awesome_flutter: ^10.5.0
  im_stepper: ^1.0.1+1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "images/icon/ic_launcher2.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: LexendExa
      fonts:
        - asset: fonts/LexendExa-Regular.ttf
    - family: PTsans
      fonts:
        - asset: fonts/PTSans-RegularItalic.ttf
    - family: MyFlutterApp
      fonts:
        - asset: icons/MyFlutterApp.ttf
    - family: MyFlutterAppSecond
      fonts:
        - asset: icons/MyFlutterAppSecond.ttf
    - family: Montserrat-Black
      fonts:
        - asset: fonts/Montserrat-Black.ttf
    - family: Montserrat-Light
      fonts:
        - asset: fonts/Montserrat-Light.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
